### ISSUE TITLE
Innovation Showcase Website

### ISSUE THREAD

**Issue by fieldsey** [GSA/CoE-MPP#1]
# Innovation Showcase Website

## Deadlines

* **Q&A period ends:** Please provide feedback or ask any questions you may have in the comments below no later than Wednesday, September 25, 2019, noon, eastern.
* **Responses due by:** Please provide your responses via [this Google Form](https://docs.google.com/forms/d/e/1FAIpQLSc1-5TVSbIwqUfJx0Aq1J2ynzw1MX8y-l_lpXP8s1wcarmd-g/viewform) no later than Friday, September 27, 2019, noon, eastern.

## Background

The Innovation Showcase is a website that will include multiple prototypes for public viewing. The intention is to start the Showcase on [the Federalist platform](https://federalistapp.18f.gov/), where built-in tools and templates are available and can be modified. 

### The project

The objectives of the Showcase are:

* Put one prototype on the Federalist platform.

### The user story

As a user, I need to be able to access a URL that will display a prototype that is located on Federalist. 

## Our expectations

Ready to view live website that is hosted on the Federalist platform.
 
### Deliverables

This is a list of deliverables that the government is expecting to obtain as a result of this CoE MPP buy:

* Codebase in HTML/Markdown on GitHub.
* Live site on Federalist.

### Definition of Done / Acceptance Criteria

This will be considered done when the website’s source code is saved on GitHub and when the prototype is live on Federalist.

### Time estimate

The government needs this user story to be completed within two weeks from the start of the associated sprint.

### Cost estimate

In accordance with Federal Acquisition Regulation (FAR) [13.2 - Actions At or Below the Micro-Purchase Threshold](https://acquisition.gov/content/part-13-simplified-acquisition-procedures#i1111868), please note that services performed under this Request for Quote (RFQ) may not exceed the Micro-Purchase Threshold, [currently set at $10,000.00](https://www.gsa.gov/cdnstatic/Policy_Initiatives/Class%20Deviation%202018-01%20MPT%20and%20SAT%20Increase.pdf).

## Disclaimer

In performance of this effort, the awardee must not perform a function that requires access to a government system or sensitive information (e.g., system administrator privileged access to a government system, or contractor systems or processes that utilize sensitive information). In order to avoid potential conflicts of interest, the awardee will not be provided any non-public information to develop the deliverables.

The awardee must not connect one or more awardee-owned IT devices to an internal trusted government network. Additionally, all deliverables must be made publicly available in this GitHub repository and in accordance with the [18F Open Source Policy](https://18f.gsa.gov/open-source-policy/), unless the government indicates otherwise. Finally, this award does not involve the storage, generating, transmitting, or exchanging of sensitive information.

## Purchase order clauses

* [FAR 52.204-13](https://www.acquisition.gov/content/52204-13-system-award-management-maintenance#i1064160) System for Award Management Maintenance (OCT 2018)
* [FAR 52.227-14](https://www.acquisition.gov/content/52227-14alternate-v#i1052520) Alternate IV Rights in Data—General (DEC 2007)
* [FAR 52.232-33](https://www.acquisition.gov/content/52232-33-payment-electronic-funds-transfer-system-award-management#i1050674) Payment by Electronic Funds Transfer—System for Award Management (OCT 2018)
* [FAR 52.232-39](https://www.acquisition.gov/content/52232-39-unenforceability-unauthorized-obligations#i1050840) Unenforceability of Unauthorized Obligations (JUN 2013)

**Comment by belucid** [comment]
Am I understanding this correctly... It doesn't matter what the prototype does, it's just to validate that you can get something up and going on the Federalist platform?

Are there any particular parts of the Federalist platform that the prototype should utilize? Or that would be ideal if the prototype utilized?

Is it a goal (or ideal) to get feedback on the Federalist platform by the team building the prototype?

**Comment by fieldsey** [comment]
In response to [this question](https://github.com/GSA/CoE-MPP/issues/1#issuecomment-533371673), please see our response, below:

> Am I understanding this correctly... It doesn't matter what the prototype does, it's just to validate that you can get something up and going on the Federalist platform?

We will provide an existing prototype that is currently hosted elsewhere. We would like to have it actually publicly accessible on the Federalist hosted site, not just validate it can be posted there.

> Are there any particular parts of the Federalist platform that the prototype should utilize? Or that would be ideal if the prototype utilized?

Initially, we simply want the ability to view the prototype on the Federalist-hosted website using pre-existing templates. Future work will involve developing additional features, including those that will take advantage of certain other capabilities available through Federalist.

> Is it a goal (or ideal) to get feedback on the Federalist platform by the team building the prototype?

While feedback on the Federalist platform will be greatly appreciated, as we accept and appreciate all feedback (e.g., our indefinite RFIs for advice on our procurement processes), that is not a goal of this solicitation.

**Comment by Git-dyp** [comment]
Q1.  So you want us to submit any innovative project on a web page using templates available at https://federalist.18f.gov/documentation/templates/?

Q2.  _"We will provide an existing prototype that is currently hosted elsewhere. We would like to have it actually publicly accessible on the Federalist hosted site, not just validate it can be posted there."_

We have no idea what this means.

Q3.  Is it required the page we submit use Jekyll or Gatsby?  Or just use the page layout template?

Q4.  On pg 3 of the submission form, it asks us to outline proposed solution and timeframe to complete.  What is the proposed solution?  The actual innovative project we are submitting or the webpage we are submitting?

Q5.  On pg 5, it asks for a quote.  Is this the quote for us to build and submit the project page?  Assuming this isn't to actually develop the innovative project the page contains.  Please clarify.

Q6.  _"While feedback on the Federalist platform will be greatly appreciated, as we accept and appreciate all feedback (e.g., our indefinite RFIs for advice on our procurement processes), that is not a goal of this solicitation."_

So what is the goal of this solicitation?

**Comment by RobOK2050** [comment]
Two questions regarding the desired integration of the prototype:

Can the government confirm there are no data fields or end-user GUI controls for the prototype that we have to integrate into the new Federalist page?
 
Is the prototype fully self-contained and operational in a non-Federalist environment today and we need to provide access to that environment?

Do we have to move the prototype and/or edit any code within the prototype itself?

Thank you!

**Comment by Git-dyp** [comment]
We plan to submit single web page that contains the video of a recent project along with text description.  It will use the page layout template.  The page will be hosted on our servers.  

1.  Is this sufficient and meet the requirement?
2.  And again, do you want us to price the LOE effort to create this page?

**Comment by fieldsey** [comment]
>So you want us to submit any innovative project on a web page using templates available at https://federalist.18f.gov/documentation/templates/?

Yes.

>"We will provide an existing prototype that is currently hosted elsewhere. We would like to have it actually publicly accessible on the Federalist hosted site, not just validate it can be posted there." We have no idea what this means.

Sorry we weren’t clear! Let us try again. For the purposes of this hypothetical, imagine Prototype-A is sitting on URL-A. We want the Innovation Showcase website to be hosted at URL-B. We want a user visiting URL-B to be able to view and interact with Prototype-A that is currently hosted on URL-A. Hopefully that makes more sense?

>Is it required the page we submit use Jekyll or Gatsby? Or just use the page layout template?
Page layout template.

>On pg 3 of the submission form, it asks us to outline proposed solution and timeframe to complete. What is the proposed solution? The actual innovative project we are submitting or the webpage we are submitting?

This field should provide us with your proposed solution to creating the Innovation Showcase website on the Federalist platform and having an external prototype accessible through that website. Anything you think would be helpful to allow us to evaluate your technical approach, processes, tools, etc. would be appropriate in terms of a response.

>On pg 5, it asks for a quote. Is this the quote for us to build and submit the project page? Assuming this isn't to actually develop the innovative project the page contains. Please clarify.

Yes, you are right, this is the quote from a contractor built and submit the project page, not to develop the actual innovative project (what we are calling a prototype) itself.

>"While feedback on the Federalist platform will be greatly appreciated, as we accept and appreciate all feedback (e.g., our indefinite RFIs for advice on our procurement processes), that is not a goal of this solicitation."
So what is the goal of this solicitation?

To get the Innovation Showcase website up and running on the Federalist platform with one externally-hosted prototype available for users to view and interact with.

**Comment by fieldsey** [comment]
>Two questions regarding the desired integration of the prototype:
Can the government confirm there are no data fields or end-user GUI controls for the prototype that we have to integrate into the new Federalist page?

Yes, this is confirmed, there are no data fields or end-user GUI controls that have to be integrated into the Innovation Showcase webpage.

>Is the prototype fully self-contained and operational in a non-Federalist environment today and we need to provide access to that environment?

Yes, this is accurate.

>Do we have to move the prototype and/or edit any code within the prototype itself?

No.

**Comment by fieldsey** [comment]
>We plan to submit single web page that contains the video of a recent project along with text description. It will use the page layout template. The page will be hosted on our servers.
>1. Is this sufficient and meet the requirement?

Some of it is, but some of it is not. We do want one single webpage that will contain an accessible prototype, hosted somewhere else. It will not be a video, but it will have some text description. It must use a Federalist template. It must be hosted on Federalist, not your server.

>2. And again, do you want us to price the LOE effort to create this page?

Yes, we would like you to provide us with your price as well as the labor mix you intend to use. Please see our [pricing sheet](https://github.com/GSA/CoE-MPP/blob/master/Pricing%20Templates/Pricing-Sheet-Innovation-Showcase-Website.xlsx) for more details on exactly what we’re looking for from contractors.

**Comment by fieldsey** [comment]
Responses for this Issue will no longer be accepted. We appreciate the time invested by all those who participated, whether they submitted a response or not. A summary of the data associated with the responses will be posted to the README.md file in the subfolder created should an award be issued.

**Comment by modiware** [comment]
The google form will not accept my submission. This happened before the deadline. Can you please help?

**Comment by oghaffari** [comment]
Please stand by, @modiware - you are the only person to say you have had issues with our form and we'd like to learn more.

**Comment by modiware** [comment]
@oghaffari Thank you for your support and quick response. I have my submission prepared and ready to go. Please advise the best way to submit. 

> Please stand by, @modiware - you are the only person to say you have had issues with our form and we'd like to learn more.

**Comment by fieldsey** [comment]
Innovation Showcase Website has been awarded to Arc Aspicio, LLC in the amount of $5,560.24. The deliverables are due at the end of the day on Tuesday, October 8, 2019.

Thank you to all those who participated!

**Comment by DaveW001** [comment]
Hello US government staff who ran this procurement. Appreciate the innovative nature of what you did. Since you are looking at being consistent with the manifesto and agile procurement practices, I'd propose you consider having interactive calls to discuss requirements with potential vendors during the solicitation process in the future. Interactive communications is a great path to innovative solutions.
